name: Panda
options:
  bundleIdPrefix: com.zhangxfeng.panda
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: zh-Hans
  xcodeVersion: 15.0

settings:
  SWIFT_VERSION: 5.9
  DEVELOPMENT_TEAM: ""

targets:
  Panda:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Panda
        excludes:
          - "**/.DS_Store"
    info:
      path: Panda/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.zhangxfeng.panda.app
      INFOPLIST_FILE: Panda/Info.plist
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1,2"
      ENABLE_PREVIEWS: true
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      DEVELOPMENT_ASSET_PATHS: ""
    dependencies: []
    scheme:
      gatherCoverageData: true
